# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Explorations of Black Literature
tagline:          'A Class'
description:      'Description'
url:              http://samanthaks.github.io/Explorations-Black-Lit
baseurl:          /

author:
  name:           'Samantha Stultz'
  url:            http://samanthaks.github.io

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/samanthaks/Explorations-Black-Lit
