# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Explorations of Black Literature
url:              http://samanthaks.github.io/Explorations-Black-Lit/
baseurl:          /Explorations-Black-Lit/

author:
  name:           'Samantha Stultz'
  url:            http://samanthaks.github.io


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/samanthaks/Explorations-Black-Lit
